# Generated by Django 2.1.7 on 2019-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/image')),
                ('video', models.FileField(blank=True, help_text='Upload only mp4, etc..', null=True, upload_to='image/video')),
                ('current_user', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Coaching',
                'db_table': 'coaching',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/image')),
                ('video', models.FileField(blank=True, help_text='Upload only mp4, etc..', null=True, upload_to='image/video')),
                ('current_user', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'School',
                'db_table': 'shool',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/image')),
                ('video', models.FileField(blank=True, help_text='Upload only mp4, etc..', null=True, upload_to='image/video')),
                ('current_user', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tutor',
                'db_table': 'tutor',
                'managed': True,
            },
        ),
    ]
